-- ============================================================
-- Copiloto Freelance — Esquema inicial
-- Postgres 15 / Supabase
-- ============================================================

create extension if not exists pgcrypto;

-- ---------- Tipos ----------
do $$ begin
  create type client_status as enum ('prospecto', 'activo', 'inactivo');
exception when duplicate_object then null; end $$;

do $$ begin
  create type quote_status as enum ('borrador', 'enviado', 'aprobado', 'cobrado');
exception when duplicate_object then null; end $$;

-- ---------- Utilidad: updated_at ----------
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ============================================================
-- users  (perfil de negocio, 1:1 con auth.users)
-- ============================================================
create table if not exists public.users (
  id            uuid primary key references auth.users (id) on delete cascade,
  email         text not null,
  business_name text,
  logo_url      text,
  -- { "tipo": "cbu" | "alias" | "paypal" | "mp", "valor": "...", "titular": "..." }
  payment_info  jsonb not null default '{}'::jsonb,
  currency      text  not null default 'ARS',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

drop trigger if exists users_touch on public.users;
create trigger users_touch
  before update on public.users
  for each row execute function public.touch_updated_at();

-- Alta automática del perfil al registrarse (email o Google)
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.users (id, email, business_name, logo_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================
-- clients
-- ============================================================
create table if not exists public.clients (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references public.users (id) on delete cascade,
  name            text not null,
  -- Guardar SIEMPRE en E.164 sin '+' (ej: 5491122334455) para poder armar wa.me
  whatsapp_number text,
  email           text,
  status          client_status not null default 'prospecto',
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint clients_whatsapp_digits check (
    whatsapp_number is null or whatsapp_number ~ '^[0-9]{8,15}$'
  )
);

drop trigger if exists clients_touch on public.clients;
create trigger clients_touch
  before update on public.clients
  for each row execute function public.touch_updated_at();

create index if not exists clients_user_idx on public.clients (user_id, created_at desc);

-- Evita duplicar el mismo contacto dentro de una cuenta.
-- NO hacerlo parcial (where whatsapp_number is not null): Postgres no puede
-- inferir un índice parcial en un ON CONFLICT, y el upsert de supabase-js
-- falla con 400. Los NULL ya son distintos entre sí en un índice único, así
-- que esto igual permite muchos clientes sin teléfono. Ver 0002.
create unique index if not exists clients_user_wpp_uniq
  on public.clients (user_id, whatsapp_number);

-- ============================================================
-- quotes  (presupuestos)
-- ============================================================
create table if not exists public.quotes (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.users (id) on delete cascade,
  client_id    uuid not null references public.clients (id) on delete restrict,
  number       bigint generated by default as identity,   -- correlativo legible
  title        text,
  -- [{ "description": "Diseño de landing", "amount": 150000, "qty": 1 }]
  items        jsonb not null default '[]'::jsonb,
  total_amount numeric(14,2) not null default 0,
  currency     text not null default 'ARS',
  status       quote_status not null default 'borrador',
  notes        text,
  pdf_url      text,
  valid_until  date,
  sent_at      timestamptz,
  paid_at      timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  constraint quotes_items_is_array check (jsonb_typeof(items) = 'array'),
  constraint quotes_total_positive check (total_amount >= 0)
);

drop trigger if exists quotes_touch on public.quotes;
create trigger quotes_touch
  before update on public.quotes
  for each row execute function public.touch_updated_at();

create index if not exists quotes_user_created_idx on public.quotes (user_id, created_at desc);
create index if not exists quotes_user_status_idx  on public.quotes (user_id, status);
create index if not exists quotes_client_idx       on public.quotes (client_id);

-- Sella sent_at / paid_at automáticamente al cambiar de estado
create or replace function public.stamp_quote_status()
returns trigger language plpgsql as $$
begin
  if new.status = 'enviado' and new.sent_at is null then
    new.sent_at = now();
  end if;
  if new.status = 'cobrado' and new.paid_at is null then
    new.paid_at = now();
  end if;
  return new;
end $$;

drop trigger if exists quotes_stamp_status on public.quotes;
create trigger quotes_stamp_status
  before insert or update of status on public.quotes
  for each row execute function public.stamp_quote_status();

-- ============================================================
-- Row Level Security — cada usuario ve sólo lo suyo
-- ============================================================
alter table public.users   enable row level security;
alter table public.clients enable row level security;
alter table public.quotes  enable row level security;

drop policy if exists users_self on public.users;
create policy users_self on public.users
  for all using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists clients_own on public.clients;
create policy clients_own on public.clients
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists quotes_own on public.quotes;
create policy quotes_own on public.quotes
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ============================================================
-- RPC: resumen del Dashboard (1 sola llamada, sin traer filas)
-- ============================================================
create or replace function public.dashboard_summary(p_month date default null)
returns table (
  quoted     numeric,
  collected  numeric,
  pending    numeric,
  open_count int
)
language sql stable security invoker as $$
  with m as (
    select date_trunc('month', coalesce(p_month, current_date)) as start
  )
  select
    coalesce(sum(q.total_amount) filter (
      where q.created_at >= m.start and q.created_at < m.start + interval '1 month'
    ), 0) as quoted,
    coalesce(sum(q.total_amount) filter (
      where q.status = 'cobrado'
        and q.paid_at >= m.start and q.paid_at < m.start + interval '1 month'
    ), 0) as collected,
    coalesce(sum(q.total_amount) filter (
      where q.status in ('enviado', 'aprobado')
    ), 0) as pending,
    count(*) filter (where q.status in ('borrador', 'enviado', 'aprobado'))::int as open_count
  from public.quotes q, m
  where q.user_id = auth.uid();
$$;

-- ============================================================
-- Vista de conveniencia: presupuesto + nombre/wpp del cliente
-- ============================================================
create or replace view public.quotes_with_client
with (security_invoker = true) as
select
  q.*,
  c.name            as client_name,
  c.whatsapp_number as client_whatsapp
from public.quotes q
join public.clients c on c.id = q.client_id;

-- ============================================================
-- Storage: logos y PDFs (bucket privado, path = {user_id}/...)
-- ============================================================
insert into storage.buckets (id, name, public)
values ('quotes', 'quotes', false)
on conflict (id) do nothing;

drop policy if exists quotes_storage_own on storage.objects;
create policy quotes_storage_own on storage.objects
  for all to authenticated
  using (bucket_id = 'quotes' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'quotes' and (storage.foldername(name))[1] = auth.uid()::text);
